// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWeather(arg1) {
  return window['go']['main']['App']['GetWeather'](arg1);
}

export function GetWeatherBundle(arg1) {
  return window['go']['main']['App']['GetWeatherBundle'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}
